spring:
  application:
    name: booking-service

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.travelhub: DEBUG